/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './toast-directive';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from '@angular/core/src/linker/view';
class ToastContainerModuleInjector extends import0.NgModuleInjector<import1.ToastContainerModule> {
  _ToastContainerModule_0:import1.ToastContainerModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.ToastContainerModule {
    this._ToastContainerModule_0 = new import1.ToastContainerModule();
    return this._ToastContainerModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ToastContainerModule)) { return this._ToastContainerModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ToastContainerModuleNgFactory:import0.NgModuleFactory<import1.ToastContainerModule> = new import0.NgModuleFactory(ToastContainerModuleInjector,import1.ToastContainerModule);
export class Wrapper_ToastContainerDirective {
  /*private*/ _eventHandler:Function;
  context:import1.ToastContainerDirective;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import1.ToastContainerDirective(p0);
  }
  ngOnDetach(view:import3.AppView<any>,componentView:import3.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import3.AppView<any>,componentView:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import3.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}